### PR TITLE
Fixed: Studio scene table should wrap very long  scene titles

### LINKED ISSUE #206: V3 scene table in performer view causes horizontal scroll
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When the title of a scene is really long, the it tirggers a horizontal scroll instead of wrapping the title to a new line or truncating it with an ellipsis.
image

### Expected Behavior

Either wrap the title to a new line or overflow (hide) with an ellipsis.

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS: Linux
- Whisparr: 3.0.0.530
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: Firefox
- Database: SQLite
```

### What branch are you running?

Develop

### Trace Logs?

available but likely not needed

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by plz12345**
Fixed: Scene row in Performer view should wrap long title

#### Database Migration
NO

#### Description
I removed the whitespace wrap on the title and performer columns as well as the and hard-coded width on the performer column.  Tested in landscape & portrait on desktop, tablet, and mobile phone screen sizes.

#### Screenshot (if UI related)
Before
image

After
image

#### Todos
- [X] Tests
- [X] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [X] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR
* Fixes #206

### CODE REVIEW

**Comment by plz12345** [comment]
Build pipeline appears to be broken again.  My change didn't touch the back end code at all.

**Comment by sampulsar** [comment]
@plz12345 

https://docs.github.com/en/desktop/managing-commits/squashing-commits-in-github-desktop

**Comment by plz12345** [comment]
@sampulsar thanks for that.  That process is so much easier in Github Desktop than VS Code.

**Comment by plz12345** [comment]
or not, wtf...

**Comment by plz12345** [comment]
I'm going to redo the branch, can't get the squash to work properly after doing it incorrectly before.

**Pull request closed without merging**
