### PR TITLE
New: Add Studio Performer Exclusions

### LINKED ISSUE #188: V3: Blocklist
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Unable to blocklist studios or scenes.

### Describe the solution you'd like

Would like to blocklist so that they don't get added and take up space.

### Describe alternatives you've considered

None

### Anything else?

Requested per Plz from another issue.

### PR DESCRIPTION
**Pull request by sampulsar**
#### Database Migration
YES - ImportExclusions Add Type

#### Description
Allow an Exclusion to be added for a Studio or Performer. This will then add a Scene exclusion.

The Exclusions not have a type and can be added via /settings/importlists

#### Screenshot (if UI related)

image

#### Todos
- [x] Tests
- [x] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [x] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes #188

### CODE REVIEW

**Comment by plz12345** [comment]
Could this work without adding the scene exclusions, too?  That list isn't optimized for large quantities, in both page loading as well as lack of bulk management.  I'd worry it could eventually start to be a performance issue when viewing the Import Lists page.  I know the trade-off would be that Whisparr would evaluate the same scenes for studio exclusions on every list sync, but it'd be doing that either way against the exclusions list itself.

**Comment by sampulsar** [comment]
@plz12345 

The exclusions are on the scenes id as this reduces the load on the skyhook server, as studios and performers only list the scene ids. This server is hosted and the hosting costs money, so retrieving a performers list of scenes and constantly retrieving some scenes daily, just to discard the data will increase the cost of this server.

If the majority of scenes are excluded then likely an import list should be used.

**Comment by plz12345** [comment]
> @plz12345 
> 
> 
> 
> The exclusions are on the scenes id as this reduces the load on the skyhook server, as studios and performers only list the scene ids. This server is hosted and the hosting costs money, so retrieving a performers list of scenes and constantly retrieving some scenes daily, just to discard the data will increase the cost of this server.
> 
> 
> 
> If the majority of scenes are excluded then likely an import list should be used.

I'm using import lists exclusively.  I'm going to use tag exclusions to avoid stuff like VR that I don't care about.  Maybe I will take a crack at making the exclusion list view more efficient to scale. No worries.

**Comment by plz12345** [comment]
I refactored the import exclusion table a bit, but will wait for this PR to merge and rebase.  The only C# code I touched is a translation, which @sampulsar probably already covered.

**Pull request closed without merging**
