### PR TITLE
FIx: Qbittorrent unknown download state issue

### LINKED ISSUE #260: DownloadItemStatus mismatch with QBitTorrent API causing completed downloads to not be imported [v3]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Whisparr logs present with the following message and completed downloads are not being imported:

`2024-10-09 07:52:25.5|Info|QBittorrent|Unknown download state: stoppedUP`

This also means the completed download is left in a `DownloadItemStatus.Downloading` state because it doesn't match any of the cases present at [QBittorrent.cs#L298](https://github.com/Whisparr/Whisparr/blob/a85a59122bd91cd75718ff4fbe4cf2df3a800687/src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs#L298)

This happens because qBittorrent is giving the completed downloads a state of `stoppedUP` instead of what Whisparr is expecting of `pausedUP`

### Expected Behavior

Completed downloads should be imported.

### Steps To Reproduce

1. Using the latest version of Whisparr:V3 and [QBittorrent:5.0.0](https://github.com/qbittorrent/qBittorrent/releases/tag/release-5.0.0) as the configured download client.
2. Add a new scene to trigger a download using the configured download client
3. Download a torrent to completion
4. Once the torrent has completed, Whisparr logs will show the unknown download state

### Environment

```markdown
- OS: N/A
- Whisparr: 3.0.0.614
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: N/A
- Database: Sqlite 3.44.2
```

### What branch are you running?

eros

### Trace Logs?
[whisparr.trace.txt](https://github.com/user-attachments/files/17317347/whisparr.trace.txt)

### Anything else?

- QBittorrent download state changes [src/webui/api/serialize/serialize_torrent.cpp](https://github.com/qbittorrent/qBittorrent/commit/5d1c2496063b41874e85af0145b153e006fc92d3#diff-74790edbe4766657bffad7700b1a73f606a7692cee56f1e093c7357ecdaea915)

### PR DESCRIPTION
**Pull request by enymawse**
#### Database Migration
NO

#### Description
Wouldn't build without updating the nuget packages. Then updates the switch that handles the download states from qbittorrent to work with two of the updates torrent states as described in #260.

#### Screenshot (if UI related)
N/A

#### Todos
- [x] Tests
- [x] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [x] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes #260

### CODE REVIEW

**Comment by sampulsar** [comment]
Should bump System.Text.Json 6.0.9 to 6.0.10 as this is the fix for version 6.

**Review by Tom-Estes — CHANGES_REQUESTED** [review]
Can you remove the JSON bump from the commit and squash? It was updated in a separate commit.

**Comment by enymawse** [comment]
> Can you remove the JSON bump from the commit and squash? It was updated in a separate commit.

Removed JSON bump.

**Review by Tom-Estes — APPROVED** [review]

**Comment by jeremysherriff** [comment]
@Tom-Estes any chance this can get merged into develop? Or would that need a different PR?

**Pull request merged**
