### PR TITLE
Adjusted search behavior to also return results by Studio+Scene combo, rather than relying on date match on those parts individually.

### LINKED ISSUE #115: Search string to include scene name or otherwise be customizable
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I am having issues finding scenes for particular sites where releases don't match the site + date search scheme that Whisparr is expecting.

### Describe the solution you'd like

It would be great if additional combinations of search strings were tried as well if no results are found, such as site + scene name.

### Describe alternatives you've considered

Alternative, customizable search strings that could be overridden per site could really benefit here as well for sites that have limited release availability. The user could provide a string with predefined tokens that get populated at search time.

`{site} {title} {date}`

### Anything else?

```
2023-09-11 23:33:02.8|Info|ReleaseSearchService|Searching indexers for [Lustery : Jason - How We Tantra]. 1 active indexers
2023-09-11 23:33:02.8|Debug|Newznab|Downloading Feed http://prowlarr:9696/1/api?t=search&cat=6000,6010,6070,6080,6045,6050,6020,6030,6040&extended=1&apikey=(removed)&offset=0&limit=100&q=Lustery+23.09.03
2023-09-11 23:33:02.8|Trace|HttpClient|Req: [GET] http://prowlarr:9696/1/api?t=search&cat=6000,6010,6070,6080,6045,6050,6020,6030,6040&extended=1&apikey=(removed)&offset=0&limit=100&q=Lustery+23.09.03
2023-09-11 23:33:02.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-09-11 23:33:03.6|Trace|HttpClient|Res: [GET] http://prowlarr:9696/1/api?t=search&cat=6000,6010,6070,6080,6045,6050,6020,6030,6040&extended=1&apikey=(removed)&offset=0&limit=100&q=Lustery+23.09.03: 200.OK (281 bytes) (796 ms)
2023-09-11 23:33:03.6|Debug|Newznab|Downloading Feed http://prowlarr:9696/1/api?t=search&cat=6000,6010,6070,6080,6045,6050,6020,6030,6040&extended=1&apikey=(removed)&offset=0&limit=100&q=lustery+23.09.03
2023-09-11 23:33:03.6|Trace|RateLimitService|Rate Limit triggered, delaying 'prowlarr' for 1.202 sec
2023-09-11 23:33:04.8|Trace|HttpClient|Req: [GET] http://prowlarr:9696/1/api?t=search&cat=6000,6010,6070,6080,6045,6050,6020,6030,6040&extended=1&apikey=(removed)&offset=0&limit=100&q=lustery+23.09.03
2023-09-11 23:33:04.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-09-11 23:33:05.2|Trace|HttpClient|Res: [GET] http://prowlarr:9696/1/api?t=search&cat=6000,6010,6070,6080,6045,6050,6020,6030,6040&extended=1&apikey=(removed)&offset=0&limit=100&q=lustery+23.09.03: 200.OK (281 bytes) (391 ms)
2023-09-11 23:33:05.2|Debug|ReleaseSearchService|Total of 0 reports were found for [Lustery : Jason - How We Tantra] from 1 indexers
2023-09-11 23:33:05.2|Debug|ReleaseSearchService|Setting last search time to: 09/12/2023 04:33:05
2023-09-11 23:33:05.2|Info|DownloadDecisionMaker|No results found
```

### PR DESCRIPTION
**Pull request by nod44**
#### Database Migration
NO

#### Problem Statement 
The goal of this PR is to address the core issues raised in #132.   The general use case for this is to improve torrent results by avoiding the common situation where the date is not part of the tracker's title.  The goal is to provide more results by not forcing a date query.  That said, queries on the Studio name unbounded by date make little sense, requiring a bit of rewiring in how the dates are injected.

#### Description (edited)
This PR adds a non-date bound "scene name" plus "studio name" combination search.  This delivers much better results to the system to pick a good release.  It does this by modifying the SearchService to have a bit more sophisticated behavior.  To facilitate this, the Trackers no longer inject dates, this is done at the service level.  (The trackers seem to be consistent in their implementation.)

The affect of this change is that user will see more results in interactive mode.  **This does not affect the parsing behavior yet**, so we shouldn't see a flood of mismatches.

##### Example Searches
- `Studio Name 12.09.22` > _Same as before_
- `StudioName 12.09.22` > _Same as before_
- `Scene Name 12.09.22` > _Same as before_
-  `Scene Name StudioName` > _New_
-  `Scene Name Studio Name` > _New_

##### Future work
- This changes does not affect release parsing, so it will not enable automatic downloads, even if there is an exact match on the title and studio.  This will need to be handed with a config option (due to higher risk of mismatch), and a different PR.
- This change does not allow aliasing or other data which may represent the studio name.   Conceivably this is the type of metadata which would be in the stashdb or local stash instance.  Executing searches with this metadata would pull back more results and might make sense.

#### Todos
- [x] Tests
- [X] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [x] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes #115

### CODE REVIEW

**Comment by nod44** [comment]
@Tom-Estes After a bunch of testing I am now happy with this change.  There is more work to do but this seems big enough as is.  Can you take a look?

**Comment by Simpuhl** [comment]
Nice

**Comment by Tom-Estes** [comment]
> @Tom-Estes After a bunch of testing I am now happy with this change.  There is more work to do but this seems big enough as is.  Can you take a look?

I'll take a look this weekend since there's a lot of moving parts. Did you test to make sure it still searches movies correctly?

**Comment by nod44** [comment]
> > @Tom-Estes After a bunch of testing I am now happy with this change.  There is more work to do but this seems big enough as is.  Can you take a look?
> 
> I'll take a look this weekend since there's a lot of moving parts. Did you test to make sure it still searches movies correctly?

Yes it appears it does. My testing approach was to check the powlar logs, and I fixed a few regressions.

**Comment by Tom-Estes** [comment]
Can you clean up https://github.com/Whisparr/Whisparr/commit/5955f0070712067719f816aa29716f414bf60532? It includes code from #239 that was already merged. Then squash the last commit into it.

**Comment by Tom-Estes** [comment]
Closing, merged under #276

**Pull request closed without merging**
