### PR TITLE
New: Monitor performers via Lists

### PR DESCRIPTION
**Pull request by Qstick**
#### Database Migration
NO

#### Description
Lists to monitor performers

#### Todos
- [ ] Tests

### CODE REVIEW

**Comment by salesawagnerpe** [comment]
any news?

**Comment by guim31** [comment]
That would be awesome ;)

**Comment by i-am-at0m** [comment]
Um I think this might be broken it has added so many sites and it's monitoring every episode on every single one

**Comment by thezak48** [comment]
> Um I think this might be broken it has added so many sites and it's monitoring every episode on every single one

You need to set monitor to specific episodes
image

**Comment by guim31** [comment]
Dumb question sorry : how do I install this version of whisparr ?

**Comment by thezak48** [comment]
> Dumb question sorry : how do I install this version of whisparr ?

it is in the nightly builds

**Comment by guim31** [comment]
> > Dumb question sorry : how do I install this version of whisparr ?
> 
> it is in the nightly builds

Here is the source I use in my Unraid setup : cr.hotio.dev/hotio/whisparr:nightly

Should I be more precise on which nighlty build I want ?

**Comment by thezak48** [comment]
as long as you are running the latest build then you will have it

**Pull request merged**
